<a href="https://colab.research.google.com/github/vvrgit/EV_Scheduling/blob/main/Electricity_Price_Forecasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
# import libraries.
import numpy as np
from sklearn.preprocessing import StandardScaler
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
import pandas as pd
import math as mt
import random

In [3]:
data = pd.read_csv('/content/drive/MyDrive/EV Scheduling/ANN_Data_2.csv')
data.head()

,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,...,F90,F91,F92,F93,F94,F95,F96,Season,Day_Status,Price
0,1999.11,1999.35,1999.50,1999.44,1999.24,1999.01,1899.81,1899.55,1899.07,1899.03,...,2579.56,2529.60,2505.44,2203.39,2202.41,2189.75,2149.47,2,1,2000.15
1,1999.35,1999.50,1999.44,1999.24,1999.01,1899.81,1899.55,1899.07,1899.03,1899.06,...,2529.60,2505.44,2203.39,2202.41,2189.75,2149.47,2000.15,2,1,2000.00
2,1999.50,1999.44,1999.24,1999.01,1899.81,1899.55,1899.07,1899.03,1899.06,1800.55,...,2505.44,2203.39,2202.41,2189.75,2149.47,2000.15,2000.00,2,1,1999.99
3,1999.44,1999.24,1999.01,1899.81,1899.55,1899.07,1899.03,1899.06,1800.55,1899.51,...,2203.39,2202.41,2189.75,2149.47,2000.15,2000.00,1999.99,2,1,1999.84
4,1999.24,1999.01,1899.81,1899.55,1899.07,1899.03,1899.06,1800.55,1899.51,1899.69,...,2202.41,2189.75,2149.47,2000.15,2000.00,1999.99,1999.84,2,1,1999.78

In [4]:
data.describe()

,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,...,F90,F91,F92,F93,F94,F95,F96,Season,Day_Status,Price
count,72960.000000,72960.000000,72960.000000,72960.000000,72960.000000,72960.000000,72960.000000,72960.000000,72960.000000,72960.000000,...,72960.000000,72960.000000,72960.000000,72960.000000,72960.000000,72960.000000,72960.000000,72960.000000,72960.000000,72960.000000
mean,5658.516518,5658.535922,5658.555008,5658.574088,5658.591926,5658.607709,5658.622941,5658.638316,5658.653549,5658.668652,...,5662.485920,5662.511024,5662.534598,5662.555256,5662.574264,5662.593287,5662.611624,1.031579,0.285992,5662.629819
std,3159.861901,3159.843776,3159.825878,3159.807987,3159.791003,3159.775601,3159.760638,3159.745076,3159.729633,3159.714296,...,3160.609606,3160.592392,3160.575439,3160.559729,3160.543095,3160.526445,3160.510177,0.823383,0.451889,3160.493773
min,998.400000,998.400000,998.400000,998.400000,998.400000,998.400000,998.400000,998.400000,998.400000,998.400000,...,998.400000,998.400000,998.400000,998.400000,998.400000,998.400000,998.400000,0.000000,0.000000,998.400000
25%,3330.327500,3330.337500,3330.340000,3330.340000,3330.340000,3330.340000,3330.340000,3330.340000,3330.340000,3330.340000,...,3330.655000,3330.660000,3330.682500,3330.690000,3330.697500,3330.715000,3330.727500,0.000000,0.000000,3330.730000
50%,4400.970000,4400.970000,4400.970000,4400.970000,4400.970000,4400.970000,4400.970000,4400.970000,4400.970000,4400.970000,...,4404.705000,4404.795000,4404.795000,4404.795000,4404.795000,4404.795000,4404.795000,1.000000,0.000000,4404.795000
75%,7500.050000,7500.050000,7500.050000,7500.050000,7500.050000,7500.050000,7500.050000,7500.050000,7500.050000,7500.050000,...,7500.172500,7500.172500,7500.172500,7500.172500,7500.172500,7500.172500,7500.172500,2.000000,1.000000,7500.172500
max,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,...,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,2.000000,1.000000,20000.000000

In [5]:
from sklearn.preprocessing import MinMaxScaler
scalar = MinMaxScaler()
load_data = scalar.fit_transform(data)
print(load_data)

[[0.05266451 0.05267714 0.05268504 ... 1.         1.         0.05271924]
 [0.05267714 0.05268504 0.05268188 ... 1.         1.         0.05271135]
 [0.05268504 0.05268188 0.05267135 ... 1.         1.         0.05271082]
 ...
 [0.13074162 0.13009536 0.12781187 ... 1.         0.         0.13640746]
 [0.13009536 0.12781187 0.12716982 ... 1.         0.         0.13310669]
 [0.12781187 0.12716982 0.12596255 ... 1.         0.         0.13044059]]

In [6]:
df = pd.DataFrame(load_data)
df

,0,1,2,3,4,5,6,7,8,9,...,89,90,91,92,93,94,95,96,97,98
0,0.052665,0.052677,0.052685,0.052682,0.052671,0.052659,0.047439,0.047425,0.047400,0.047398,...,0.083212,0.080583,0.079311,0.063415,0.063364,0.062697,0.060578,1.0,1.0,0.052719
1,0.052677,0.052685,0.052682,0.052671,0.052659,0.047439,0.047425,0.047400,0.047398,0.047399,...,0.080583,0.079311,0.063415,0.063364,0.062697,0.060578,0.052719,1.0,1.0,0.052711
2,0.052685,0.052682,0.052671,0.052659,0.047439,0.047425,0.047400,0.047398,0.047399,0.042215,...,0.079311,0.063415,0.063364,0.062697,0.060578,0.052719,0.052711,1.0,1.0,0.052711
3,0.052682,0.052671,0.052659,0.047439,0.047425,0.047400,0.047398,0.047399,0.042215,0.047423,...,0.063415,0.063364,0.062697,0.060578,0.052719,0.052711,0.052711,1.0,1.0,0.052703
4,0.052671,0.052659,0.047439,0.047425,0.047400,0.047398,0.047399,0.042215,0.047423,0.047432,...,0.063364,0.062697,0.060578,0.052719,0.052711,0.052711,0.052703,1.0,1.0,0.052700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72955,0.135911,0.133010,0.130742,0.130095,0.127812,0.127170,0.125963,0.125944,0.121177,0.113271,...,0.315863,0.250083,0.210629,0.194833,0.171166,0.179602,0.171100,1.0,0.0,0.158630
72956,0.133010,0.130742,0.130095,0.127812,0.127170,0.125963,0.125944,0.121177,0.113271,0.111145,...,0.250083,0.210629,0.194833,0.171166,0.179602,0.171100,0.158630,1.0,0.0,0.136398
72957,0.130742,0.130095,0.127812,0.127170,0.125963,0.125944,0.121177,0.113271,0.111145,0.106476,...,0.210629,0.194833,0.171166,0.179602,0.171100,0.158630,0.136398,1.0,0.0,0.136407
72958,0.130095,0.127812,0.127170,0.125963,0.125944,0.121177,0.113271,0.111145,0.106476,0.105913,...,0.194833,0.171166,0.179602,0.171100,0.158630,0.136398,0.136407,1.0,0.0,0.133107
72959,0.127812,0.127170,0.125963,0.125944,0.121177,0.113271,0.111145,0.106476,0.105913,0.105390,...,0.171166,0.179602,0.171100,0.158630,0.136398,0.136407,0.133107,1.0,0.0,0.130441

In [7]:
a = df.iloc[0:69985,0:99]
b = df.iloc[69985:,0:99]
print(a.shape)
print(b.shape)

(69985, 99)
(2975, 99)

In [8]:
x = a.iloc[:,0:98].values
y = a.iloc[:,98].values
x1 = b.iloc[:, 0:98].values
y1 = b.iloc[:, 98].values
print(x.shape)
print(y.shape)

(69985, 98)
(69985,)

In [9]:
print(x)
print('--------------')
print(y)

[[0.05266451 0.05267714 0.05268504 ... 0.06057753 1.         1.        ]
 [0.05267714 0.05268504 0.05268188 ... 0.05271924 1.         1.        ]
 [0.05268504 0.05268188 0.05267135 ... 0.05271135 1.         1.        ]
 ...
 [0.1090645  0.10876084 0.10546059 ... 0.10903766 1.         1.        ]
 [0.10876084 0.10546059 0.10544849 ... 0.1053827  1.         1.        ]
 [0.10546059 0.10544849 0.10538165 ... 0.10545533 1.         0.        ]]
--------------
[0.05271924 0.05271135 0.05271082 ... 0.1053827  0.10545533 0.09746442]

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, train_size=0.8, test_size=0.2, random_state=0)

In [11]:
X_train.shape

(55988, 98)

In [12]:
import keras  #Keras is the deep learning library that helps you to code Deep Neural Networks with fewer lines of code
#from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense
from tensorflow.keras.optimizers import RMSprop,Adadelta,SGD,Adagrad,Adam

In [13]:
model = Sequential()
model.add(Dense(78,activation='relu', input_shape=(98,)))
model.add(Dense(78,activation='relu'))
model.add(Dense(78,activation='relu'))
model.add(Dense(78,activation='relu'))
model.add(Dense(78,activation='relu'))
model.add(Dense(78,activation='relu'))
model.add(Dense(1,activation='sigmoid')) #output Layer
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 78)             │         7,722 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 78)             │         6,162 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 78)             │         6,162 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 78)             │         6,162 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 78)             │         6,162 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 78)             │         6,162 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 1)              │            79 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 38,611 (150.82 KB)

 Trainable params: 38,611 (150.82 KB)

 Non-trainable params: 0 (0.00 B)

In [21]:
model.compile(loss='MSE',
              optimizer=Adam(),
              metrics=['MSE'])

In [22]:
# Write the Training input and output variables, size of the batch, number of epochs
history = model.fit(X_train,y_train,
                    batch_size=32,
                    epochs=10,verbose=1)

Epoch 1/10
1750/1750 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - MSE: 0.0012 - loss: 0.0012
Epoch 2/10
1750/1750 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - MSE: 0.0011 - loss: 0.0011
Epoch 3/10
1750/1750 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - MSE: 0.0011 - loss: 0.0011
Epoch 4/10
1750/1750 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - MSE: 0.0011 - loss: 0.0011
Epoch 5/10
1750/1750 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - MSE: 0.0010 - loss: 0.0010
Epoch 6/10
1750/1750 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - MSE: 0.0010 - loss: 0.0010
Epoch 7/10
1750/1750 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - MSE: 0.0010 - loss: 0.0010
Epoch 8/10
1750/1750 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - MSE: 9.9889e-04 - loss: 9.9889e-04
Epoch 9/10
1750/1750 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - MSE: 9.9678e-04 - loss: 9.9678e-04
Epoch 10/10
1750/1750 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - MSE: 9.9628e-04 - loss: 9.9628e-04

In [23]:
# Write the testing input and output variables
score = model.evaluate(X_test, y_test, verbose=2)
print('Test loss:', score[0])

438/438 - 1s - 2ms/step - MSE: 0.0010 - loss: 0.0010
Test loss: 0.0010052184807136655

In [24]:
model.save("my_model_relu_78_6.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [25]:
min_val = data.min()
print(min_val)
max_val = data.max()
print(max_val)

F1            998.4
F2            998.4
F3            998.4
F4            998.4
F5            998.4
              ...
F95           998.4
F96           998.4
Season          0.0
Day_Status      0.0
Price         998.4
Length: 99, dtype: float64
F1            20000.0
F2            20000.0
F3            20000.0
F4            20000.0
F5            20000.0
               ...
F95           20000.0
F96           20000.0
Season            2.0
Day_Status        1.0
Price         20000.0
Length: 99, dtype: float64

In [26]:
min_val = min_val[98]
max_val = max_val[98]

/tmp/ipykernel_898/2003783787.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  min_val = min_val[98]
/tmp/ipykernel_898/2003783787.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  max_val = max_val[98]

In [28]:
from keras.models import load_model
from keras.metrics import MeanSquaredError

# Provide custom_objects to load_model for built-in metrics that might cause deserialization issues
model = load_model('/content/my_model_relu_78_6.h5', custom_objects={'MSE': MeanSquaredError()})

# List or array containing predicted values
predicted_values = model.predict(x1)

# List or array containing actual values
actual_values = y1

# Flatten the predicted values to convert them into a 1D array
predicted_values_flat = np.squeeze(predicted_values)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

93/93 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [29]:
print(predicted_values_flat.shape)
print(actual_values.shape)

(2975,)
(2975,)

In [30]:
# Inverse normalization to get the original values
predicted_values_original = []
actual_values_original = []
for i in range(len(actual_values)):
  predicted_values_original.append(predicted_values_flat[i] * (max_val - min_val) + min_val)
  actual_values_original.append(actual_values[i] * (max_val - min_val) + min_val)

In [31]:

# Creating a DataFrame to store the predicted and actual values
data = {'Actual': actual_values_original, 'Predicted': predicted_values_original}
df = pd.DataFrame(data)

# Specifying the file path in Google Drive to save the Excel file
file_path = '/content/predicted_actual_values_mape_unseen.xlsx'

# Writing the DataFrame to an Excel file in Google Drive
df.to_excel(file_path, index=False)

print(f"Predicted and actual values saved to {file_path}")

Predicted and actual values saved to /content/predicted_actual_values_mape_unseen.xlsx

In [32]:
df.head()

    Actual    Predicted
0  2733.12  2991.668312
1  2840.08  2841.620661
2  2830.47  2866.127364
3  2489.74  2813.596012
4  2489.53  2658.439135